// Sample data extracted from ServicesPage
export const allServices = [
    {
        id: 1,
        title: "Professional House Cleaning",
        price: 180,
        priceText: "From 180 MAD",
        provider: "Sara Cleaning Services",
        providerImage:
            "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Casablanca",
        distance: 2.1,
        rating: 4.9,
        reviews: 127,
        image:
            "https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "Deep cleaning, regular maintenance, eco-friendly products. Trusted by 500+ families.",
        tags: ["Eco-Friendly", "Insured", "Same Day"],
        responseTime: 2,
        responseTimeText: "< 2 hours",
        badges: ["AI Match", "Verified"],
        category: "House Cleaning",
        availability: "24/7",
        experience: 5,
        completedJobs: 500,
        isEmergency: false,
        phone: "+212 6 12 34 56 78",
        email: "sara@cleaningservices.ma",
    },
    {
        id: 2,
        title: "Emergency Plumbing Services",
        price: 250,
        priceText: "From 250 MAD",
        provider: "Ahmed Plumbing Solutions",
        providerImage:
            "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Casablanca",
        distance: 3.5,
        rating: 4.8,
        reviews: 94,
        image:
            "https://images.pexels.com/photos/8487806/pexels-photo-8487806.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "24/7 emergency service, leak repairs, pipe installation. Licensed and experienced.",
        tags: ["Emergency Service", "24/7 Available", "Licensed"],
        responseTime: 0.5,
        responseTimeText: "< 30 mins",
        badges: ["Verified", "Emergency"],
        category: "Plumbing",
        availability: "24/7",
        experience: 8,
        completedJobs: 300,
        isEmergency: true,
        phone: "+212 6 23 45 67 89",
        email: "ahmed@plumbingpro.ma",
    },
    {
        id: 3,
        title: "AC Maintenance & Repair",
        price: 200,
        priceText: "From 200 MAD",
        provider: "CoolTech Services",
        providerImage:
            "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Casablanca",
        distance: 4.2,
        rating: 4.7,
        reviews: 78,
        image:
            "https://images.pexels.com/photos/7031590/pexels-photo-7031590.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "AC installation, repair, and maintenance. All brands serviced with warranty.",
        tags: ["Warranty Included", "All Brands", "Certified"],
        responseTime: 4,
        responseTimeText: "< 4 hours",
        badges: ["AI Match", "Verified"],
        category: "AC Repair",
        availability: "Mon-Sat",
        experience: 6,
        completedJobs: 200,
        isEmergency: false,
        phone: "+212 6 34 56 78 90",
        email: "info@cooltech.ma",
    },
    {
        id: 4,
        title: "Electrical Installation & Repair",
        price: 150,
        priceText: "From 150 MAD",
        provider: "ElectricPro Services",
        providerImage:
            "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Rabat",
        distance: 5.1,
        rating: 4.6,
        reviews: 56,
        image:
            "https://images.pexels.com/photos/8853502/pexels-photo-8853502.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "Safe electrical work, wiring, fixtures, and emergency repairs. Licensed electrician.",
        tags: ["Licensed", "Safety Certified", "Insured"],
        responseTime: 6,
        responseTimeText: "< 6 hours",
        badges: ["Verified"],
        category: "Electrical Work",
        availability: "Mon-Fri",
        experience: 10,
        completedJobs: 400,
        isEmergency: false,
        phone: "+212 6 45 67 89 01",
        email: "contact@electricpro.ma",
    },
    {
        id: 5,
        title: "Interior & Exterior Painting",
        price: 300,
        priceText: "From 300 MAD",
        provider: "ColorCraft Painters",
        providerImage:
            "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Casablanca",
        distance: 6.0,
        rating: 4.8,
        reviews: 89,
        image:
            "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "Professional painting services with premium materials. Color consultation included.",
        tags: ["Color Consultation", "Premium Materials", "Eco Paint"],
        responseTime: 12,
        responseTimeText: "< 12 hours",
        badges: ["AI Match", "Verified"],
        category: "Painting",
        availability: "Mon-Sat",
        experience: 7,
        completedJobs: 150,
        isEmergency: false,
        phone: "+212 6 56 78 90 12",
        email: "info@colorcraft.ma",
    },
    {
        id: 6,
        title: "Appliance Repair Services",
        price: 120,
        priceText: "From 120 MAD",
        provider: "FixIt Appliance Solutions",
        providerImage:
            "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Casablanca",
        distance: 7.2,
        rating: 4.5,
        reviews: 43,
        image:
            "https://images.pexels.com/photos/4107113/pexels-photo-4107113.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "Washing machines, refrigerators, dishwashers. Quick diagnostics and repair.",
        tags: ["All Appliances", "Quick Service", "Warranty"],
        responseTime: 8,
        responseTimeText: "< 8 hours",
        badges: ["Verified"],
        category: "Appliance Repair",
        availability: "Mon-Sat",
        experience: 4,
        completedJobs: 100,
        isEmergency: false,
        phone: "+212 6 67 89 01 23",
        email: "support@fixit.ma",
    },
    {
        id: 7,
        title: "Professional Handyman Services",
        price: 100,
        priceText: "From 100 MAD",
        provider: "HandyFix Solutions",
        providerImage:
            "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Rabat",
        distance: 8.5,
        rating: 4.4,
        reviews: 67,
        image:
            "https://images.pexels.com/photos/5691659/pexels-photo-5691659.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "General repairs, furniture assembly, small installations. Reliable and affordable.",
        tags: ["Multi-Service", "Affordable", "Reliable"],
        responseTime: 3,
        responseTimeText: "< 3 hours",
        badges: ["Verified"],
        category: "Handyman",
        availability: "Mon-Sat",
        experience: 3,
        completedJobs: 80,
        isEmergency: false,
        phone: "+212 6 78 90 12 34",
        email: "info@handyfix.ma",
    },
    {
        id: 8,
        title: "Moving & Relocation Services",
        price: 400,
        priceText: "From 400 MAD",
        provider: "MoveEasy Transport",
        providerImage:
            "https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
        location: "Fes",
        distance: 12.0,
        rating: 4.7,
        reviews: 92,
        image:
            "https://images.pexels.com/photos/7464230/pexels-photo-7464230.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop",
        description: "Professional moving services with packing, loading, and transportation.",
        tags: ["Full Service", "Insured", "Professional Team"],
        responseTime: 24,
        responseTimeText: "< 24 hours",
        badges: ["AI Match", "Verified"],
        category: "Moving",
        availability: "Mon-Sun",
        experience: 9,
        completedJobs: 250,
        isEmergency: false,
        phone: "+212 6 89 01 23 45",
        email: "booking@moveeasy.ma",
    },
]

export const categories = [
    { name: "House Cleaning", count: 245 },
    { name: "Plumbing", count: 189 },
    { name: "Electrical Work", count: 156 },
    { name: "AC Repair", count: 132 },
    { name: "Painting", count: 98 },
    { name: "Appliance Repair", count: 87 },
    { name: "Handyman", count: 76 },
    { name: "Moving", count: 54 },
]

export const locations = ["Casablanca", "Rabat", "Fes", "Marrakech", "Agadir", "Tangier", "Oujda", "Kenitra"]

export const availabilityOptions = [
    { value: "24/7", label: "24/7 Available" },
    { value: "Mon-Sun", label: "7 Days a Week" },
    { value: "Mon-Sat", label: "Monday to Saturday" },
    { value: "Mon-Fri", label: "Weekdays Only" },
]
